Fix win32 build
aeternity/emcl pull request #3
Opened 2019-11-26 08:57 UTC by tolbrino

2019-11-26 10:24 UTC, hanssv approved these changes

2019-11-29 10:04 UTC, hanssv requested changes
I think all tests should be run?

2019-11-29 10:04 UTC, hanssv commented on c_src/emcl_nif.c
> +}
Indentation?

2019-11-29 10:04 UTC, hanssv commented on c_src/emcl_nif.c
> +  mclBnFr z;
Hmm... If you are payed per-line, but otherwise?? 🤔

2019-11-29 10:04 UTC, hanssv commented on test/emcl_tests.erl
> +%mul_vec_test() ->
I think these tests are fine now?

2019-11-29 12:00 UTC, tolbrino commented on test/emcl_tests.erl
> +%mul_vec_test() ->
Fixed.

2019-11-29 12:06 UTC, hanssv approved these changes

2019-11-29 12:07 UTC, merged